server:
  port: 8888
spring:
  application:
    name: pcs-system
#  mysql\u914D\u7F6E
  datasource:
#    url: jdbc:mysql://10.103.244.129:3306/pcs?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://10.103.240.237:3306/psc1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa\u914D\u7F6E
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://10.103.246.113:8000/eureka
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    prefer-ip-address: true
